#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if git diff --cached --name-only | grep -q "^src/"; then
    bun run checkTs
    bun run lint-staged
    NODE_ENV=production bun run build
    git add build/
fi
